language: objective-c

osx_image: xcode8.4
xcode_workspace: PCFPush.xcworkspace
xcode_scheme: ALL PCFPushSpecs
xcode_sdk: iphonesimulator9.3

notifications:
    webhooks:
      - http://pulse.pivotallabs.com/projects/ebfc1f38-8ae7-4469-a9d4-c924880e1bda/status

before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install && cd $TRAVIS_BUILD_DIR
